telegram_token: "6622111915:AAFPMXJRqri1b1LjQKH9S82Okm8Sdqjpta8"
allowed_telegram_usernames: []  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as positive integers and/or channel ids as negative integers
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)